### ISSUE TITLE
Open API documentation generation - support for recursive directories

### ISSUE THREAD

**Issue by RaviVaranasi** [cesarParra/apexdocs#179]
Thanks for creating this to improve the documentation of the salesforce apex code.  I tried to upgrade to 3.0 version of apex-docs. The earlier version used to look for recursive references within `force-app/main/default` (we have sub-folders under `classes`)

<img width="399" alt="Screenshot 2024-09-19 at 9 18 11 AM" src="https://github.com/user-attachments/assets/b432f2cd-b9f0-4088-8810-f209d64af6b9">

Command i run:
`apexdocs openapi -s force-app/main/default/classes --title 'Custom API documentation'  -g openapi --openApiFileName api-file`

It does detect the documentation files

<img width="882" alt="Screenshot 2024-09-19 at 9 22 13 AM" src="https://github.com/user-attachments/assets/c01a777d-185e-494c-a04b-59cbd6aebcb7">

`apexdocs openapi -s force-app/main/default/classes/rest --title 'Custom API documentation'  -g openapi --openApiFileName api-file`

It throws a reference error

<img width="1654" alt="Screenshot 2024-09-19 at 9 23 07 AM" src="https://github.com/user-attachments/assets/3110f5ca-fe5f-49c1-a908-949599e7f2ce">

**Comment by cesarParra** [comment]
Hi @RaviVaranasi 

Thanks for reporting the issue.

I'm having a bit of a hard time replicating the issue. Here is what I am trying:

* I tried to create a similar folder structure to your image, which looks like this

![image](https://github.com/user-attachments/assets/f51710c8-44c7-4b19-bf4e-4e5400a1d4be)

* I am running the following command

```
apexdocs openapi -s force-app/main/default/classes --title 'Custom API documentation' --openApiFileName api-file
```

(by the way, there is no need to specify the -g flag anymore since the second part of the command already specifies that an openapi spec should be generated).

* And that results in the following output

![image](https://github.com/user-attachments/assets/b06063fc-730d-4ba4-a1b8-49c9d47e73da)

Let me know if this looks different from your set up and I can try to replicate with something that looks more similar to what you have.

**Comment by cesarParra** [comment]
Thanks @RaviVaranasi 

Let me investigate

**Comment by cesarParra** [comment]
@RaviVaranasi 

I believe I have identified the issue and I've released version 3.1.1 with it. Please let me know if that resolves it, otherwise feel free to reopen this.

By the way, in v3 there are a few changes to the flags, so the command you are trying to use needs a couple of minor adjustments.

First is that the `-g` flag is no longer necessary, since that is now being handled by calling the `apexdocs openapi` subcommand, which already will know to generate the OpenApi spec and not markdown.

The other thing is that now that `openapi` has its own subcommand, the `openApiFileName` has been renamed to just be `fileName`, since now the flags are specific to each subcommand and not shared, so I was able to clean that up a bit. So now your command should look something more like

```
apexdocs openapi -s force-app/main/default/classes --title 'Custom API documentation' --fileName api-file
```

**Comment by RaviVaranasi** [comment]
That was fast but will confirm if that fixed it

**Comment by RaviVaranasi** [comment]
That fixed the issue 🚀 🎉 . Appreciate the quick turnaround
