### ISSUE TITLE
Example output of changelog

### ISSUE THREAD

**Issue by RaviVaranasi** [cesarParra/apexdocs#186]
Can you show an example output of the `changelog` command? Is a good use case to show the documentation difference in a PR?

**Comment by cesarParra** [comment]
Right now the output is a markdown file, since the use case I had in mind was to combine it with the `markdown` command to create a more robust doc site.

Here's how the `vitepress` example I have on the repo looks like

![image](https://github.com/user-attachments/assets/9d741da1-13e8-45b8-854c-89c319fcf9ab)

But I really like that use case!

I was already planning on providing the ability to use the changelog command by providing 2 git refs (one before and after the changes) so once I work on that I can keep this use case in mind to see how it can be integrated with whatever output a VCS might need to add it as a comment in the PR

**Comment by cesarParra** [comment]
@RaviVaranasi I prototyped a quick-and-dirty example on how the command can be used to add comments in a PR using Github Actions

Here is how the GH action looks:
https://github.com/cesarParra/expression/blob/prototype/changelog/.github/workflows/changelog.yaml

And here is how the comment in the PR looks:
https://github.com/cesarParra/expression/pull/162#issuecomment-2388367128

I just wanted to test out what could be done today before I make any additional changes and this is just a super simple prototype so it doesn't take care of cleaning up any outdated comments or any of that.
