### ISSUE TITLE
Allow multiple @author and @date tags

### ISSUE THREAD

**Issue by dschach** [cesarParra/apexdocs#33]
Sometimes a method can have multiple `@author` and `@date` tags to show original and subsequent authors. Currently, the generated site only shows the last one.

**Comment by HerrX2000** [comment]
@dschach Is there any somewhat standardized annotation format for that? I have seen markdown tables being used e.g.:
/*
* @history
* |    Date               |    Author           |    Description                            
* |----------------------|---------------------|---------------------------------------------------
* |    2022-01-17    |    me                |    initial release
 */

**Comment by dschach** [comment]
@HerrX2000 The Javadoc standard for author is at https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#@author
Javadoc uses `since` instead of `date` and only one, so we only need one `since` or `date` tag.

**Comment by cesarParra** [comment]
Thanks for the request @dschach, I'll see what I can do. 

As a note this is already supported in version 2 of this tool [2.0.0-alpha.15](https://www.npmjs.com/package/@cparra/apexdocs/v/2.0.0-alpha.15) if you want to check that out in the meantime (there are still some features that I haven't migrated to it yet so I'm still treating that as alpha until I do).

**Comment by cesarParra** [comment]
Ok, so I have a version of this working, but before I upload a new version I wanted to double check the display expectations for this @dschach .

Currently what I have looks like this
![image](https://user-images.githubusercontent.com/2524257/157879331-6c0f1727-8ad0-4fad-a18a-07ec956fca54.png)

As you can see all authors are printed first and then all dates. Does this look ok or would it make more sense to have something more similar to what @HerrX2000 mentioned, and instead create some sort of history table so that the authors and the date of the contribution are grouped together.

**Comment by dschach** [comment]
@cesarParra I love this! I'm still unsure what I think about multiple date tags, but if it supports it, then why not? The multiple author tags is key! Thank you very much.

**Comment by cesarParra** [comment]
@dschach excellent.

I just pushed [1.15.0](https://www.npmjs.com/package/@cparra/apexdocs/v/1.15.0) with this functionality.
