### ISSUE TITLE
Option to filter out certain files

### ISSUE THREAD

**Issue by TijsDeBelie** [cesarParra/apexdocs#40]
Add an option to filter out files, especially useful for managed packages that only have a (hidden) content. 

Add option to ignore files without comments or with a certain annotation

**Comment by cesarParra** [comment]
Thanks for the suggestion @TijsDeBelie .

One way to filter out files currently is through access modifier (global, public, protected, private). So if you have a managed package and you only want to document what is exposed, you would use global.

Would that work or are you looking to also be able to exclude certain files based on other criteria?

**Comment by TijsDeBelie** [comment]
Thank you for the quick response, this already helps filter out a lot of the spam, thanks. 
Our issue was that Field service lightning managed package had 80+ apex classes and they were in our way in the documentation

**Comment by cesarParra** [comment]
No problem!

Another option if you want to ignore files that you don't own is isolating your code to live within a specific directory, and specifying that directory when running the command. Though would only work if you are using the SFDX tooling to deploy the code (otherwise all of your code needs to live under the same `classes` folder).

Let me know if you are good with those suggestions and I can go ahead and close this, or if you want me to look into providing something different as well, not a problem at all
