### ISSUE TITLE
Feature Request: Better Class-level descriptions with Markdown

### ISSUE THREAD

**Issue by jclark-dot-org** [cesarParra/apexdocs#58]
I'd like to have some longer form explanatory text at the top of my class files.  With the recent addition of HTML support, this is (mostly) possible, but I'd prefer to use markdown.  Markdown largely already works in apexdocs, but `@description` treats all content as one long unformatted span (unless you add html tags).  Here's a (shortened) example of a class header I'd like to use.  Note that I could use `<p>`, `<ul>`, and `<li>` tags for the beginning, but I still can't do a code block.  
````
/**********************************************************
@class          TriggerService
@testClass      TriggerService_Test
@group          core-utils
@description    Simple Trigger Framework, integrated with <<CodeControl>>.

To use TriggerService for a given trigger,
1.  Build a trigger handler class that extends <<TriggerHelperBase>>, implementing any trigger stages (e.g., beforeInsert, afterUpdate, etc)
    needed by your trigger.
2.  In the trigger, call `TriggerService.run()`, passing a new instance of your handler.

```
// TriggerHandler
public class AccountHandler extends TriggerHelperBase {
    public override void afterInsert(List<SObject> newList) {
        // ... do trigger things
    }
}

// Trigger
trigger AccountTrigger on Account (after insert) {
    TriggerService.run(new AccountHandler());
}
```
@author         Jason Clark
@date           1/15/22
***********************************************************/
````
What I'd like is a way to specify the description is a block, and pass any standard markdown.  Maybe `@description-block` and `@end-block` tags?

**Comment by cesarParra** [comment]
Thanks for the suggestion @jclark-dot-org 

I have a version of this in the latest beta release here: https://www.npmjs.com/package/@cparra/apexdocs/v/2.6.0-beta.3. 

Here's how it works:
* I've added the support to the standard `@description` tag, so now the formatting should be respected rather than everything being grouped within a single block of text.
* Previously all HTML (except those in the whitelist) where sanitized. Now there's a new flag called `--sanitizeHtml` that, when turned off, will allow you to have any kind of HTML in there (could be helpful if you want to also style things). 

Now, the main reason for HTML sanitization was actually to prevent [this bug](https://github.com/cesarParra/apexdocs/issues/22) from happening. So its good to be aware of that when turning that off. I have detailed how to solve those issues in the **HTML support** section of the documentation for the version linked above.

Would be great if you can test it out and let me know of any suggestions, issues, or improvements to the way I've implemented it. Otherwise, if things look good let me know and I will release this in the GA channel.

**Comment by cesarParra** [comment]
Ah, that is probably cause the text sanitization/trimming is now too aggressive given that we want to preserve whitespaces. Looking into it.

**Comment by cesarParra** [comment]
@jclark-dot-org I've changed the way sanitization works in the latest version (https://www.npmjs.com/package/@cparra/apexdocs/v/2.6.0-beta.4). Hopefully this one works better, feel free to try it out and let me know.
